### ISSUE TITLE
style="format %d)"

### ISSUE THREAD

**Issue by mnot** [reschke/xml2rfc#5] opened 2015-09-24 02:50 UTC
List with style="format %d)" (for example) seem to be broken; the style is honoured, but if there are multiple lists, numbering doesn't restart for each list; instead, all list items in the entire document use the same number space.

**Comment by reschke** [comment] 2015-09-24 05:35
Example, please.

**Comment by mnot** [comment] 2015-09-24 05:41
http://mnot.github.io/I-D/http-key/

(created with:
  https://github.com/mnot/RFCbootstrap/blob/master/rfcbootstrap.xslt
... which should cause you great joy.)

**Comment by reschke** [comment] 2015-09-24 06:32
OK, this behaves as intended (for some value of "intended"). Apparently it's inconsistent between xml2rfc implementations and underspecified.

I'll have to think about this, but for now the easiest way to reset the counters is to add a counter="some-unique-name" attribute to each list.

**Comment by mnot** [comment] 2015-09-24 07:15
Thanks.

**Comment by reschke** [comment] 2020-08-20 10:13
Fixed in https://github.com/reschke/xml2rfc/commit/15d29a24ba3972f9b0ae426ab581dc9f1f92d778 by removing the obsole grouping support.

**Closed as completed by reschke** 2020-08-20 10:13 UTC
